add airbnb eslint
nmassardot/doesnt-follow-back pull request #3
Opened 2022-06-30 03:30 UTC by Baelfire18

## What?

- Add airbnb eslint
- Add eslint commands
- Autocorrect eslint
- Correct eslint errors
- Add eslint rules

## Why?

To standardize code rules

## How?

Installing the package, running the commands and fixing if necessary.

2022-07-01 18:34 UTC, nmassardot requested changes
Change the rule from single quotes to double quotes please
Thanks for your contribution!

2022-07-01 18:34 UTC, nmassardot commented on README.md
> +This proyect uses the airbnb eslint style guide. For runing it, you can use the following command:
```suggestion
This proyect uses the airbnb eslint style guide. For running it, you can use the following command:
```

2022-07-01 18:34 UTC, nmassardot commented on README.md
> +yarn lint # To check linting
```suggestion
yarn lint # Check linting
```

2022-07-01 18:34 UTC, nmassardot commented on README.md
> +yarn lint --fix # To fix autocorrectable linting
```suggestion
yarn lint --fix # Automatic fix linting
```

2022-07-01 18:34 UTC, nmassardot commented on src/App.test.jsx
> +/* eslint-enable no-undef */
Delete this file plz, no test in here

2022-07-01 18:34 UTC, nmassardot commented on src/components/SectionFollowers.jsx
> +              {' '}
Delete the double space

2022-07-01 18:34 UTC, nmassardot commented on src/components/logos/GithubLogo.jsx
> +      className={className}
I prefer this with props, in case I need something else

2022-07-01 23:05 UTC, Baelfire18 commented
All changes requestes (including erasing the test 😢) done!
Also resolved conflict, and it also passes the linter

2022-07-03 22:28 UTC, nmassardot approved these changes

2022-07-03 22:28 UTC, merged